// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AddTransactionItemInput struct {
	TransactionID  string  `json:"transactionId"`
	ItemID         string  `json:"itemId"`
	FromLocationID *string `json:"fromLocationId,omitempty"`
	ToLocationID   *string `json:"toLocationId,omitempty"`
	Quantity       float64 `json:"quantity"`
	BatchNumber    *string `json:"batchNumber,omitempty"`
	Reason         *string `json:"reason,omitempty"`
	Notes          *string `json:"notes,omitempty"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateCustomerAccountInput struct {
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	Phone          *string `json:"phone,omitempty"`
	AddressLine1   *string `json:"addressLine1,omitempty"`
	AddressLine2   *string `json:"addressLine2,omitempty"`
	City           *string `json:"city,omitempty"`
	State          *string `json:"state,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Country        *string `json:"country,omitempty"`
	TaxID          *string `json:"taxId,omitempty"`
	Notes          *string `json:"notes,omitempty"`
	Status         *string `json:"status,omitempty"`
}

type CreateIntegrationConfigInput struct {
	OrganizationID string `json:"organizationId"`
	Name           string `json:"name"`
	Type           string `json:"type"`
	APIKey         string `json:"apiKey"`
	APISecret      string `json:"apiSecret"`
}

type CreateInventoryTransactionInput struct {
	OrganizationID  string  `json:"organizationId"`
	Type            string  `json:"type"`
	ReferenceNumber string  `json:"referenceNumber"`
	Notes           *string `json:"notes,omitempty"`
}

type CreateItemCategoryInput struct {
	OrganizationID   string  `json:"organizationId"`
	ParentCategoryID *string `json:"parentCategoryId,omitempty"`
	Name             string  `json:"name"`
	Description      *string `json:"description,omitempty"`
}

type CreateItemInput struct {
	CategoryID    string          `json:"categoryId"`
	Sku           string          `json:"sku"`
	Name          string          `json:"name"`
	Description   *string         `json:"description,omitempty"`
	Quantity      float64         `json:"quantity"`
	UnitOfMeasure string          `json:"unitOfMeasure"`
	MinimumStock  *float64        `json:"minimumStock,omitempty"`
	MaximumStock  *float64        `json:"maximumStock,omitempty"`
	ReorderPoint  *float64        `json:"reorderPoint,omitempty"`
	CostPrice     *int            `json:"costPrice,omitempty"`
	SellingPrice  *int            `json:"sellingPrice,omitempty"`
	Msrp          *int            `json:"msrp,omitempty"`
	Barcode       *string         `json:"barcode,omitempty"`
	Image         *graphql.Upload `json:"image,omitempty"`
	Weight        *float64        `json:"weight,omitempty"`
	Dimensions    *string         `json:"dimensions,omitempty"`
}

type CreateLocationInput struct {
	PlaceID          string  `json:"placeId"`
	ParentLocationID *string `json:"parentLocationId,omitempty"`
	Name             string  `json:"name"`
	Type             string  `json:"type"`
	Description      *string `json:"description,omitempty"`
}

type CreateOrganizationInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	AdminEmail  string  `json:"adminEmail"`
	TaxID       *string `json:"taxId,omitempty"`
	LogoURL     *string `json:"logoUrl,omitempty"`
}

type CreatePermissionInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreatePlaceInput struct {
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	AddressLine1   string  `json:"addressLine1"`
	AddressLine2   *string `json:"addressLine2,omitempty"`
	City           string  `json:"city"`
	State          string  `json:"state"`
	PostalCode     string  `json:"postalCode"`
	Country        string  `json:"country"`
}

type CreateRoleInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateSupplierInput struct {
	OrganizationID string  `json:"organizationId"`
	Name           string  `json:"name"`
	ContactName    *string `json:"contactName,omitempty"`
	Email          *string `json:"email,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	AddressLine1   *string `json:"addressLine1,omitempty"`
	AddressLine2   *string `json:"addressLine2,omitempty"`
	City           *string `json:"city,omitempty"`
	State          *string `json:"state,omitempty"`
	PostalCode     *string `json:"postalCode,omitempty"`
	Country        *string `json:"country,omitempty"`
	PaymentTerms   *string `json:"paymentTerms,omitempty"`
	TaxID          *string `json:"taxId,omitempty"`
	Notes          *string `json:"notes,omitempty"`
	Status         string  `json:"status"`
}

type CreateSupplierItemInput struct {
	SupplierID  string   `json:"supplierId"`
	ItemID      string   `json:"itemId"`
	SupplierSku *string  `json:"supplierSku,omitempty"`
	UnitCost    *int     `json:"unitCost,omitempty"`
	Moq         *float64 `json:"moq,omitempty"`
	LeadTime    *int     `json:"leadTime,omitempty"`
	IsPreferred *bool    `json:"isPreferred,omitempty"`
}

type CreateUserInput struct {
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateCustomerAccountInput struct {
	Name         *string `json:"name,omitempty"`
	Email        *string `json:"email,omitempty"`
	Password     *string `json:"password,omitempty"`
	Phone        *string `json:"phone,omitempty"`
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	City         *string `json:"city,omitempty"`
	State        *string `json:"state,omitempty"`
	PostalCode   *string `json:"postalCode,omitempty"`
	Country      *string `json:"country,omitempty"`
	TaxID        *string `json:"taxId,omitempty"`
	Notes        *string `json:"notes,omitempty"`
	Status       *string `json:"status,omitempty"`
}

type UpdateIntegrationConfigInput struct {
	Name      *string `json:"name,omitempty"`
	Type      *string `json:"type,omitempty"`
	APIKey    *string `json:"apiKey,omitempty"`
	APISecret *string `json:"apiSecret,omitempty"`
	Status    *string `json:"status,omitempty"`
}

type UpdateInventoryTransactionInput struct {
	Type            *string `json:"type,omitempty"`
	ReferenceNumber *string `json:"referenceNumber,omitempty"`
	Notes           *string `json:"notes,omitempty"`
}

type UpdateItemCategoryInput struct {
	ParentCategoryID *string `json:"parentCategoryId,omitempty"`
	Name             *string `json:"name,omitempty"`
	Description      *string `json:"description,omitempty"`
}

type UpdateItemInput struct {
	CategoryID    *string         `json:"categoryId,omitempty"`
	Sku           *string         `json:"sku,omitempty"`
	Name          *string         `json:"name,omitempty"`
	Description   *string         `json:"description,omitempty"`
	Quantity      *float64        `json:"quantity,omitempty"`
	UnitOfMeasure *string         `json:"unitOfMeasure,omitempty"`
	MinimumStock  *float64        `json:"minimumStock,omitempty"`
	MaximumStock  *float64        `json:"maximumStock,omitempty"`
	ReorderPoint  *float64        `json:"reorderPoint,omitempty"`
	CostPrice     *int            `json:"costPrice,omitempty"`
	SellingPrice  *int            `json:"sellingPrice,omitempty"`
	Msrp          *int            `json:"msrp,omitempty"`
	Barcode       *string         `json:"barcode,omitempty"`
	Image         *graphql.Upload `json:"image,omitempty"`
	Weight        *float64        `json:"weight,omitempty"`
	Dimensions    *string         `json:"dimensions,omitempty"`
}

type UpdateLocationInput struct {
	PlaceID          *string `json:"placeId,omitempty"`
	ParentLocationID *string `json:"parentLocationId,omitempty"`
	Name             *string `json:"name,omitempty"`
	Type             *string `json:"type,omitempty"`
	Description      *string `json:"description,omitempty"`
}

type UpdateOrganizationInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	AdminEmail  *string `json:"adminEmail,omitempty"`
	TaxID       *string `json:"taxId,omitempty"`
	LogoURL     *string `json:"logoUrl,omitempty"`
}

type UpdatePermissionInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdatePlaceInput struct {
	Name         *string `json:"name,omitempty"`
	Type         *string `json:"type,omitempty"`
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	City         *string `json:"city,omitempty"`
	State        *string `json:"state,omitempty"`
	PostalCode   *string `json:"postalCode,omitempty"`
	Country      *string `json:"country,omitempty"`
}

type UpdateRoleInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateSupplierInput struct {
	Name         *string `json:"name,omitempty"`
	ContactName  *string `json:"contactName,omitempty"`
	Email        *string `json:"email,omitempty"`
	Phone        *string `json:"phone,omitempty"`
	AddressLine1 *string `json:"addressLine1,omitempty"`
	AddressLine2 *string `json:"addressLine2,omitempty"`
	City         *string `json:"city,omitempty"`
	State        *string `json:"state,omitempty"`
	PostalCode   *string `json:"postalCode,omitempty"`
	Country      *string `json:"country,omitempty"`
	PaymentTerms *string `json:"paymentTerms,omitempty"`
	TaxID        *string `json:"taxId,omitempty"`
	Notes        *string `json:"notes,omitempty"`
	Status       *string `json:"status,omitempty"`
}

type UpdateSupplierItemInput struct {
	SupplierID  *string  `json:"supplierId,omitempty"`
	ItemID      *string  `json:"itemId,omitempty"`
	SupplierSku *string  `json:"supplierSku,omitempty"`
	UnitCost    *int     `json:"unitCost,omitempty"`
	Moq         *float64 `json:"moq,omitempty"`
	LeadTime    *int     `json:"leadTime,omitempty"`
	IsPreferred *bool    `json:"isPreferred,omitempty"`
}

type UpdateTransactionItemInput struct {
	FromLocationID *string  `json:"fromLocationId,omitempty"`
	ToLocationID   *string  `json:"toLocationId,omitempty"`
	Quantity       *float64 `json:"quantity,omitempty"`
	BatchNumber    *string  `json:"batchNumber,omitempty"`
	Reason         *string  `json:"reason,omitempty"`
	Notes          *string  `json:"notes,omitempty"`
}

type UpdateUserInput struct {
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

type UploadItemImageInput struct {
	Image  graphql.Upload `json:"image"`
	ItemID string         `json:"itemID"`
}
